run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  govet:
    enable-all: false
