version: "2"
run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - errorlint
    - errname
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    govet:
      enable-all: false

formatters:
  enable:
    - gofmt
