// Code generated by dynac. DO NOT EDIT.

package ddb

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

// GetUser :one
func (q *Queries) GetUser(ctx context.Context, pk string, sk string) (User, error) {
	v0, err := q.marshalValue(pk)
	if err != nil {
		return User{}, invalidErr(err)
	}
	v1, err := q.marshalValue(sk)
	if err != nil {
		return User{}, invalidErr(err)
	}

	out, err := q.Client.GetItem(ctx, &dynamodb.GetItemInput{
		TableName: &q.Table,
		Key: map[string]types.AttributeValue{
			"pk": v0,
			"sk": v1,
		},
		ConsistentRead: ptrBool(true),
	})
	if err != nil {
		return User{}, normalizeError(err)
	}
	if out.Item == nil {
		return User{}, ErrNotFound
	}
	var res User
	if err := q.unmarshal(out.Item, &res); err != nil {
		return User{}, invalidErr(err)
	}
	return res, nil
}

// ListUsersByOrg :many
func (q *Queries) ListUsersByOrg(ctx context.Context, pk string, skPrefix string) ([]User, error) {
	v0, err := q.marshalValue(pk)
	if err != nil {
		return nil, invalidErr(err)
	}
	v1, err := q.marshalValue(skPrefix)
	if err != nil {
		return nil, invalidErr(err)
	}

	keyCond := "#n0 = :v0 AND begins_with(#n1, :v1)"
	exprNames := map[string]string{
		"#n0": "pk",
		"#n1": "sk",
	}
	exprVals := map[string]types.AttributeValue{
		":v0": v0,
		":v1": v1,
	}
	input := &dynamodb.QueryInput{
		TableName:                 &q.Table,
		KeyConditionExpression:    &keyCond,
		ExpressionAttributeNames:  exprNames,
		ExpressionAttributeValues: exprVals,
		Limit:                     func() *int32 { v := int32(100); return &v }(),
	}
	var res []User
	max := int32(100)
	p := dynamodb.NewQueryPaginator(q.Client, input)
	for p.HasMorePages() {
		page, err := p.NextPage(ctx)
		if err != nil {
			return nil, normalizeError(err)
		}
		for _, item := range page.Items {
			var row User
			if err := q.unmarshal(item, &row); err != nil {
				return nil, invalidErr(err)
			}
			res = append(res, row)
			if int32(len(res)) >= max {
				return res[:max], nil
			}
		}
	}
	return res, nil
}

// CreateUser :exec
func (q *Queries) CreateUser(ctx context.Context, user User) error {
	av, err := q.marshal(user)
	if err != nil {
		return invalidErr(err)
	}
	input := &dynamodb.PutItemInput{
		TableName: &q.Table,
		Item:      av,
	}
	cond := "attribute_not_exists(#pk)"
	exprNames := map[string]string{
		"#pk": "pk",
	}
	input.ConditionExpression = &cond
	input.ExpressionAttributeNames = exprNames
	_, err = q.Client.PutItem(ctx, input)
	if isConditionalFailed(err) {
		return ErrConflict
	}
	return normalizeError(err)
}

// UpdateUser :exec
func (q *Queries) UpdateUser(ctx context.Context, pk string, sk string, newEmail string) error {
	k0, err := q.marshalValue(pk)
	if err != nil {
		return invalidErr(err)
	}
	k1, err := q.marshalValue(sk)
	if err != nil {
		return invalidErr(err)
	}

	v0, err := q.marshalValue(newEmail)
	if err != nil {
		return invalidErr(err)
	}

	updateExpr := "SET #n0 = :v0"
	cond := "attribute_exists(#n1)"
	exprNames := map[string]string{
		"#n0": "email",
		"#n1": "pk",
	}
	exprVals := map[string]types.AttributeValue{
		":v0": v0,
	}
	input := &dynamodb.UpdateItemInput{
		TableName: &q.Table,
		Key: map[string]types.AttributeValue{
			"pk": k0,
			"sk": k1,
		},
		UpdateExpression:          &updateExpr,
		ConditionExpression:       &cond,
		ExpressionAttributeNames:  exprNames,
		ExpressionAttributeValues: exprVals,
	}
	_, err = q.Client.UpdateItem(ctx, input)
	if isConditionalFailed(err) {
		return ErrNotFound
	}
	return normalizeError(err)
}

// DeleteUser :exec
func (q *Queries) DeleteUser(ctx context.Context, pk string, sk string) error {
	v0, err := q.marshalValue(pk)
	if err != nil {
		return invalidErr(err)
	}
	v1, err := q.marshalValue(sk)
	if err != nil {
		return invalidErr(err)
	}

	cond := "attribute_exists(#pk)"
	exprNames := map[string]string{
		"#pk": "pk",
	}
	input := &dynamodb.DeleteItemInput{
		TableName: &q.Table,
		Key: map[string]types.AttributeValue{
			"pk": v0,
			"sk": v1,
		},
		ConditionExpression:      &cond,
		ExpressionAttributeNames: exprNames,
	}
	_, err = q.Client.DeleteItem(ctx, input)
	if isConditionalFailed(err) {
		return ErrNotFound
	}
	return normalizeError(err)
}
